services:

  frontend:
    build:
      context: ./frontend
      target: dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host

  backend.api:
    build:
      context: ./backend.api
    ports:
      - "8000:8000"
    volumes:
      - ./backend.api:/app
    environment:
      CAJA_SERVICE_URL: http://backend.caja:8000
    command:
      - uvicorn
      - app.main:app
      - --host
      - 0.0.0.0
      - --port
      - "8000"
      - --reload

  backend.caja:
    build:
      context: ./backend.caja
    volumes:
      - ./backend.caja:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_BACKEND_USER: ${MYSQL_BACKEND_USER}
      MYSQL_BACKEND_PASSWORD: ${MYSQL_BACKEND_PASSWORD}
    command:
      - uvicorn
      - app.main:app
      - --host
      - 0.0.0.0
      - --port
      - "8000"
      - --reload

  mysql:
    image: mysql:8.4
    container_name: sanjusto-caja-mysql-dev
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

    volumes:
      - mysql_data:/var/lib/mysql

    ports:
      - "127.0.0.1:3307:3306"

volumes:
  mysql_data: